package profiler

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// trackerVMA mirrors the JSON shape emitted by dirty_tracker_c.
type trackerVMA struct {
	Start      string   `json:"start"`
	End        string   `json:"end"`
	Dirty      int64    `json:"dirty"`
	Total      uint64   `json:"total"`
	Perms      string   `json:"perms"`
	Type       string   `json:"type"`
	ChunkDirty []uint16 `json:"chunk_dirty"`
}

type trackerEntry struct {
	TimestampMs float64      `json:"timestamp_ms"`
	VMADirty    []trackerVMA `json:"vma_dirty"`
}

type trackerJSON struct {
	Workload          string         `json:"workload"`
	DirtyRateTimeline []trackerEntry `json:"dirty_rate_timeline"`
}

func parseHex(s string) uint64 {
	s = strings.TrimPrefix(s, "0x")
	v, err := strconv.ParseUint(s, 16, 64)
	if err != nil {
		panic(err)
	}
	return v
}

func vmaTypeFromString(s string) VMAType {
	switch s {
	case "heap":
		return VMAHeap
	case "stack":
		return VMAStack
	case "anonymous":
		return VMAAnonymous
	case "code":
		return VMACode
	case "data":
		return VMAData
	case "vdso":
		return VMAVDSO
	}
	return VMAUnknown
}

// TestHeatClassifier_RealWorkload feeds tracker JSON output through the
// chunk-level heat classifier and verifies that the synthetic memwrite hot
// band at 64-80 MB (4 chunks at 100% dirty for >=N samples) is correctly
// flagged. Reads /tmp/wl_chunk.json, generated by running the C tracker on a
// memwrite-style workload.
func TestHeatClassifier_RealWorkload(t *testing.T) {
	const path = "/tmp/wl_chunk.json"
	if _, err := os.Stat(path); err != nil {
		t.Skipf("skip: %s not present (run tracker on VM first)", path)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var doc trackerJSON
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	timeline := doc.DirtyRateTimeline
	if len(timeline) < 3 {
		t.Fatalf("need >=3 samples, got %d", len(timeline))
	}

	heat := newHeatClassifier(0.3, 3)

	var hot []HotRegion
	for i, entry := range timeline {
		results := make([]scanResult, 0, len(entry.VMADirty))
		for _, v := range entry.VMADirty {
			start := parseHex(v.Start)
			end := parseHex(v.End)
			if end <= start {
				continue
			}
			results = append(results, scanResult{
				VMAStart:   start,
				VMAEnd:     end,
				DirtyPages: v.Dirty,
				TotalPages: v.Total,
				VMAType:    vmaTypeFromString(v.Type),
				Pathname:   "",
				ChunkDirty: append([]uint16(nil), v.ChunkDirty...),
			})
		}
		hot = heat.update(results)
		t.Logf("sample%d: scanned %d VMAs, hot_chunks=%d",
			i, len(results), len(hot))
	}

	if len(hot) == 0 {
		t.Fatalf("expected hot chunks, got 0")
	}

	sort.Slice(hot, func(i, j int) bool { return hot[i].StartAddr < hot[j].StartAddr })

	t.Logf("=== final hot chunks (%d total) ===", len(hot))
	largestVMAStart := uint64(0)
	largestSize := uint64(0)
	for _, e := range timeline[len(timeline)-1].VMADirty {
		s := parseHex(e.Start)
		end := parseHex(e.End)
		if end-s > largestSize {
			largestSize = end - s
			largestVMAStart = s
		}
	}

	hotInLargest := 0
	hotChunkOffsetsMB := []uint64{}
	for _, h := range hot {
		offsetFromLargest := h.StartAddr - largestVMAStart
		if h.StartAddr >= largestVMAStart && offsetFromLargest < largestSize {
			hotInLargest++
			hotChunkOffsetsMB = append(hotChunkOffsetsMB, offsetFromLargest/(1024*1024))
		}
		t.Logf("  chunk: 0x%x-0x%x  ratio=%.3f  consec=%d",
			h.StartAddr, h.EndAddr, h.WrittenRatio, h.ConsecutiveHot)
	}

	t.Logf("hot chunks within largest VMA (0x%x, %dMB): %d at offsets (MB) %v",
		largestVMAStart, largestSize/(1024*1024),
		hotInLargest, hotChunkOffsetsMB)

	// Expect 4 hot chunks at offsets 64, 68, 72, 76 MB (the hot band).
	if hotInLargest != 4 {
		t.Errorf("expected 4 hot chunks in largest VMA, got %d (offsets %v)",
			hotInLargest, hotChunkOffsetsMB)
	}

	expectedOffsets := map[uint64]bool{64: true, 68: true, 72: true, 76: true}
	for _, off := range hotChunkOffsetsMB {
		if !expectedOffsets[off] {
			t.Errorf("unexpected hot chunk at offset %dMB", off)
		}
	}

	fmt.Printf("ok: chunk-level classifier flagged exactly the hot band [64-80MB]\n")
}
