---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.io
  resources:
  - migratableapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.io
  resources:
  - migratableapps/finalizers
  verbs:
  - update
- apiGroups:
  - migration.io
  resources:
  - migratableapps/status
  verbs:
  - get
  - patch
  - update
