//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPolicy) DeepCopyInto(out *CheckpointPolicy) {
	*out = *in
	out.DeadlineScheduler = in.DeadlineScheduler
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPolicy.
func (in *CheckpointPolicy) DeepCopy() *CheckpointPolicy {
	if in == nil {
		return nil
	}
	out := new(CheckpointPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointStatus) DeepCopyInto(out *CheckpointStatus) {
	*out = *in
	in.LastCheckpointTime.DeepCopyInto(&out.LastCheckpointTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointStatus.
func (in *CheckpointStatus) DeepCopy() *CheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeadlineSchedulerConfig) DeepCopyInto(out *DeadlineSchedulerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeadlineSchedulerConfig.
func (in *DeadlineSchedulerConfig) DeepCopy() *DeadlineSchedulerConfig {
	if in == nil {
		return nil
	}
	out := new(DeadlineSchedulerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionMethod) DeepCopyInto(out *DetectionMethod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionMethod.
func (in *DetectionMethod) DeepCopy() *DetectionMethod {
	if in == nil {
		return nil
	}
	out := new(DetectionMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratableApp) DeepCopyInto(out *MigratableApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratableApp.
func (in *MigratableApp) DeepCopy() *MigratableApp {
	if in == nil {
		return nil
	}
	out := new(MigratableApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigratableApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratableAppList) DeepCopyInto(out *MigratableAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MigratableApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratableAppList.
func (in *MigratableAppList) DeepCopy() *MigratableAppList {
	if in == nil {
		return nil
	}
	out := new(MigratableAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigratableAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratableAppSpec) DeepCopyInto(out *MigratableAppSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	out.CheckpointPolicy = in.CheckpointPolicy
	in.MigrationPolicy.DeepCopyInto(&out.MigrationPolicy)
	in.SpotInterruptionHandling.DeepCopyInto(&out.SpotInterruptionHandling)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratableAppSpec.
func (in *MigratableAppSpec) DeepCopy() *MigratableAppSpec {
	if in == nil {
		return nil
	}
	out := new(MigratableAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigratableAppStatus) DeepCopyInto(out *MigratableAppStatus) {
	*out = *in
	if in.MigrationHistory != nil {
		in, out := &in.MigrationHistory, &out.MigrationHistory
		*out = make([]MigrationRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CheckpointStatus.DeepCopyInto(&out.CheckpointStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigratableAppStatus.
func (in *MigratableAppStatus) DeepCopy() *MigratableAppStatus {
	if in == nil {
		return nil
	}
	out := new(MigratableAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPolicy) DeepCopyInto(out *MigrationPolicy) {
	*out = *in
	if in.TargetNodeSelector != nil {
		in, out := &in.TargetNodeSelector, &out.TargetNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPolicy.
func (in *MigrationPolicy) DeepCopy() *MigrationPolicy {
	if in == nil {
		return nil
	}
	out := new(MigrationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationRecord) DeepCopyInto(out *MigrationRecord) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationRecord.
func (in *MigrationRecord) DeepCopy() *MigrationRecord {
	if in == nil {
		return nil
	}
	out := new(MigrationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpotInterruptionHandling) DeepCopyInto(out *SpotInterruptionHandling) {
	*out = *in
	if in.DetectionMethods != nil {
		in, out := &in.DetectionMethods, &out.DetectionMethods
		*out = make([]DetectionMethod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpotInterruptionHandling.
func (in *SpotInterruptionHandling) DeepCopy() *SpotInterruptionHandling {
	if in == nil {
		return nil
	}
	out := new(SpotInterruptionHandling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
