// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PreCheckpointRequest contains parameters for pre-checkpoint
type PreCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent checkpoint ID for incremental dump
	ParentDumpId string `protobuf:"bytes,1,opt,name=parent_dump_id,json=parentDumpId,proto3" json:"parent_dump_id,omitempty"`
	// Whether to upload to S3 immediately
	UploadToS3    bool `protobuf:"varint,2,opt,name=upload_to_s3,json=uploadToS3,proto3" json:"upload_to_s3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckpointRequest) Reset() {
	*x = PreCheckpointRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckpointRequest) ProtoMessage() {}

func (x *PreCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckpointRequest.ProtoReflect.Descriptor instead.
func (*PreCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PreCheckpointRequest) GetParentDumpId() string {
	if x != nil {
		return x.ParentDumpId
	}
	return ""
}

func (x *PreCheckpointRequest) GetUploadToS3() bool {
	if x != nil {
		return x.UploadToS3
	}
	return false
}

// PreCheckpointResponse contains the result of pre-checkpoint
type PreCheckpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated checkpoint ID
	DumpId string `protobuf:"bytes,1,opt,name=dump_id,json=dumpId,proto3" json:"dump_id,omitempty"`
	// Timestamp when checkpoint was created
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Size of the checkpoint in bytes
	SizeBytes int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Number of memory pages dumped
	PagesDumped   int64 `protobuf:"varint,4,opt,name=pages_dumped,json=pagesDumped,proto3" json:"pages_dumped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckpointResponse) Reset() {
	*x = PreCheckpointResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckpointResponse) ProtoMessage() {}

func (x *PreCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckpointResponse.ProtoReflect.Descriptor instead.
func (*PreCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PreCheckpointResponse) GetDumpId() string {
	if x != nil {
		return x.DumpId
	}
	return ""
}

func (x *PreCheckpointResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PreCheckpointResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PreCheckpointResponse) GetPagesDumped() int64 {
	if x != nil {
		return x.PagesDumped
	}
	return 0
}

// FinalDumpRequest contains parameters for final dump
type FinalDumpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page-server address (target pod IP)
	PageServerAddr string `protobuf:"bytes,1,opt,name=page_server_addr,json=pageServerAddr,proto3" json:"page_server_addr,omitempty"`
	// Page-server port
	PageServerPort int32 `protobuf:"varint,2,opt,name=page_server_port,json=pageServerPort,proto3" json:"page_server_port,omitempty"`
	// Parent checkpoint ID
	ParentDumpId string `protobuf:"bytes,3,opt,name=parent_dump_id,json=parentDumpId,proto3" json:"parent_dump_id,omitempty"`
	// Whether to leave process running (for testing)
	LeaveRunning bool `protobuf:"varint,4,opt,name=leave_running,json=leaveRunning,proto3" json:"leave_running,omitempty"`
	// Migration strategy: full, lazy-storage, lazy-direct, lazy-hybrid
	MigrationStrategy string `protobuf:"bytes,5,opt,name=migration_strategy,json=migrationStrategy,proto3" json:"migration_strategy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FinalDumpRequest) Reset() {
	*x = FinalDumpRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalDumpRequest) ProtoMessage() {}

func (x *FinalDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalDumpRequest.ProtoReflect.Descriptor instead.
func (*FinalDumpRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *FinalDumpRequest) GetPageServerAddr() string {
	if x != nil {
		return x.PageServerAddr
	}
	return ""
}

func (x *FinalDumpRequest) GetPageServerPort() int32 {
	if x != nil {
		return x.PageServerPort
	}
	return 0
}

func (x *FinalDumpRequest) GetParentDumpId() string {
	if x != nil {
		return x.ParentDumpId
	}
	return ""
}

func (x *FinalDumpRequest) GetLeaveRunning() bool {
	if x != nil {
		return x.LeaveRunning
	}
	return false
}

func (x *FinalDumpRequest) GetMigrationStrategy() string {
	if x != nil {
		return x.MigrationStrategy
	}
	return ""
}

// FinalDumpResponse contains the result of final dump
type FinalDumpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated checkpoint ID
	DumpId string `protobuf:"bytes,1,opt,name=dump_id,json=dumpId,proto3" json:"dump_id,omitempty"`
	// Timestamp when dump was created
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Size of metadata in bytes (pages sent via page-server)
	MetadataSizeBytes int64 `protobuf:"varint,3,opt,name=metadata_size_bytes,json=metadataSizeBytes,proto3" json:"metadata_size_bytes,omitempty"`
	// External mounts detected during dump (mountpoint -> identifier)
	ExternalMounts map[string]string `protobuf:"bytes,4,rep,name=external_mounts,json=externalMounts,proto3" json:"external_mounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// PID of page-server process (for tracking completion)
	PageServerPid int32 `protobuf:"varint,5,opt,name=page_server_pid,json=pageServerPid,proto3" json:"page_server_pid,omitempty"`
	// Pipe inodes from dumped process (label -> inode, e.g., "stdout" -> "232671")
	PipeInodes    map[string]string `protobuf:"bytes,6,rep,name=pipe_inodes,json=pipeInodes,proto3" json:"pipe_inodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalDumpResponse) Reset() {
	*x = FinalDumpResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalDumpResponse) ProtoMessage() {}

func (x *FinalDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalDumpResponse.ProtoReflect.Descriptor instead.
func (*FinalDumpResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *FinalDumpResponse) GetDumpId() string {
	if x != nil {
		return x.DumpId
	}
	return ""
}

func (x *FinalDumpResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FinalDumpResponse) GetMetadataSizeBytes() int64 {
	if x != nil {
		return x.MetadataSizeBytes
	}
	return 0
}

func (x *FinalDumpResponse) GetExternalMounts() map[string]string {
	if x != nil {
		return x.ExternalMounts
	}
	return nil
}

func (x *FinalDumpResponse) GetPageServerPid() int32 {
	if x != nil {
		return x.PageServerPid
	}
	return 0
}

func (x *FinalDumpResponse) GetPipeInodes() map[string]string {
	if x != nil {
		return x.PipeInodes
	}
	return nil
}

// RestoreRequest contains parameters for restore
type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Checkpoint ID to restore from
	DumpId string `protobuf:"bytes,1,opt,name=dump_id,json=dumpId,proto3" json:"dump_id,omitempty"`
	// S3 bucket name
	S3Bucket string `protobuf:"bytes,2,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	// S3 prefix (path to checkpoint)
	S3Prefix string `protobuf:"bytes,3,opt,name=s3_prefix,json=s3Prefix,proto3" json:"s3_prefix,omitempty"`
	// Whether to use lazy pages
	UseLazyPages bool `protobuf:"varint,4,opt,name=use_lazy_pages,json=useLazyPages,proto3" json:"use_lazy_pages,omitempty"`
	// Page-server port for lazy restore
	PageServerPort int32 `protobuf:"varint,5,opt,name=page_server_port,json=pageServerPort,proto3" json:"page_server_port,omitempty"`
	// Source pod IP address (for lazy-pages to connect to)
	SourceAddr string `protobuf:"bytes,6,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	// External mounts to use during restore (mountpoint -> identifier)
	ExternalMounts map[string]string `protobuf:"bytes,7,rep,name=external_mounts,json=externalMounts,proto3" json:"external_mounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Migration strategy: full, lazy-storage, lazy-direct, lazy-hybrid
	MigrationStrategy string `protobuf:"bytes,8,opt,name=migration_strategy,json=migrationStrategy,proto3" json:"migration_strategy,omitempty"`
	// Pipe inodes from dump (label -> inode) for --inherit-fd mapping
	PipeInodes    map[string]string `protobuf:"bytes,9,rep,name=pipe_inodes,json=pipeInodes,proto3" json:"pipe_inodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreRequest) GetDumpId() string {
	if x != nil {
		return x.DumpId
	}
	return ""
}

func (x *RestoreRequest) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *RestoreRequest) GetS3Prefix() string {
	if x != nil {
		return x.S3Prefix
	}
	return ""
}

func (x *RestoreRequest) GetUseLazyPages() bool {
	if x != nil {
		return x.UseLazyPages
	}
	return false
}

func (x *RestoreRequest) GetPageServerPort() int32 {
	if x != nil {
		return x.PageServerPort
	}
	return 0
}

func (x *RestoreRequest) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *RestoreRequest) GetExternalMounts() map[string]string {
	if x != nil {
		return x.ExternalMounts
	}
	return nil
}

func (x *RestoreRequest) GetMigrationStrategy() string {
	if x != nil {
		return x.MigrationStrategy
	}
	return ""
}

func (x *RestoreRequest) GetPipeInodes() map[string]string {
	if x != nil {
		return x.PipeInodes
	}
	return nil
}

// RestoreResponse contains the result of restore
type RestoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether restore was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// PID of the restored process
	NewPid int32 `protobuf:"varint,2,opt,name=new_pid,json=newPid,proto3" json:"new_pid,omitempty"`
	// Timestamp when restore completed
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Restore duration in milliseconds
	DurationMs    int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreResponse) GetNewPid() int32 {
	if x != nil {
		return x.NewPid
	}
	return 0
}

func (x *RestoreResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RestoreResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// StatusRequest is empty for now
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{6}
}

// StatusResponse contains the current agent status
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current mode: "normal", "restore", or "idle"
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Main process PID (0 if not found)
	MainProcessPid int32 `protobuf:"varint,2,opt,name=main_process_pid,json=mainProcessPid,proto3" json:"main_process_pid,omitempty"`
	// Last checkpoint ID
	LastCheckpointId string `protobuf:"bytes,3,opt,name=last_checkpoint_id,json=lastCheckpointId,proto3" json:"last_checkpoint_id,omitempty"`
	// Current checkpoint chain depth
	CheckpointChainDepth int32 `protobuf:"varint,4,opt,name=checkpoint_chain_depth,json=checkpointChainDepth,proto3" json:"checkpoint_chain_depth,omitempty"`
	// Node name
	NodeName string `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Pod name
	PodName string `protobuf:"bytes,6,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Agent uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Whether lazy-pages is still transferring pages (blocks checkpoints)
	LazyPagesActive bool `protobuf:"varint,8,opt,name=lazy_pages_active,json=lazyPagesActive,proto3" json:"lazy_pages_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatusResponse) GetMainProcessPid() int32 {
	if x != nil {
		return x.MainProcessPid
	}
	return 0
}

func (x *StatusResponse) GetLastCheckpointId() string {
	if x != nil {
		return x.LastCheckpointId
	}
	return ""
}

func (x *StatusResponse) GetCheckpointChainDepth() int32 {
	if x != nil {
		return x.CheckpointChainDepth
	}
	return 0
}

func (x *StatusResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *StatusResponse) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetLazyPagesActive() bool {
	if x != nil {
		return x.LazyPagesActive
	}
	return false
}

// PageServerRequest contains parameters for starting page-server
type PageServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Port to listen on
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Directory containing checkpoint images
	CheckpointDir string `protobuf:"bytes,2,opt,name=checkpoint_dir,json=checkpointDir,proto3" json:"checkpoint_dir,omitempty"`
	// Whether to run in daemon mode
	Daemon        bool `protobuf:"varint,3,opt,name=daemon,proto3" json:"daemon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageServerRequest) Reset() {
	*x = PageServerRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageServerRequest) ProtoMessage() {}

func (x *PageServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageServerRequest.ProtoReflect.Descriptor instead.
func (*PageServerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PageServerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PageServerRequest) GetCheckpointDir() string {
	if x != nil {
		return x.CheckpointDir
	}
	return ""
}

func (x *PageServerRequest) GetDaemon() bool {
	if x != nil {
		return x.Daemon
	}
	return false
}

// PageServerResponse contains the result of page-server start
type PageServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether page-server started successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Page-server PID
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Port it's listening on
	Port          int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageServerResponse) Reset() {
	*x = PageServerResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageServerResponse) ProtoMessage() {}

func (x *PageServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageServerResponse.ProtoReflect.Descriptor instead.
func (*PageServerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PageServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PageServerResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PageServerResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// PageServerStatusRequest contains parameters for checking page-server status
type PageServerStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PID of page-server to check
	Pid           int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageServerStatusRequest) Reset() {
	*x = PageServerStatusRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageServerStatusRequest) ProtoMessage() {}

func (x *PageServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageServerStatusRequest.ProtoReflect.Descriptor instead.
func (*PageServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PageServerStatusRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// PageServerStatusResponse contains the page-server status
type PageServerStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether process is still running
	IsAlive bool `protobuf:"varint,1,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	// Exit code if terminated (0 if still running)
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Human-readable status message
	StatusMessage string `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageServerStatusResponse) Reset() {
	*x = PageServerStatusResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageServerStatusResponse) ProtoMessage() {}

func (x *PageServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageServerStatusResponse.ProtoReflect.Descriptor instead.
func (*PageServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PageServerStatusResponse) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *PageServerStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *PageServerStatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// StartProfilingRequest contains parameters for starting memory write profiling
type StartProfilingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scan interval in milliseconds (default: 1000)
	IntervalMs int32 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	// Written ratio threshold for hot classification (default: 0.3)
	HotThreshold float64 `protobuf:"fixed64,2,opt,name=hot_threshold,json=hotThreshold,proto3" json:"hot_threshold,omitempty"`
	// Consecutive hot intervals to mark VMA as hot (default: 3)
	HotConsecutive int32 `protobuf:"varint,3,opt,name=hot_consecutive,json=hotConsecutive,proto3" json:"hot_consecutive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartProfilingRequest) Reset() {
	*x = StartProfilingRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProfilingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProfilingRequest) ProtoMessage() {}

func (x *StartProfilingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProfilingRequest.ProtoReflect.Descriptor instead.
func (*StartProfilingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StartProfilingRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *StartProfilingRequest) GetHotThreshold() float64 {
	if x != nil {
		return x.HotThreshold
	}
	return 0
}

func (x *StartProfilingRequest) GetHotConsecutive() int32 {
	if x != nil {
		return x.HotConsecutive
	}
	return 0
}

// StartProfilingResponse contains the result of starting profiling
type StartProfilingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	VmaCount      int32                  `protobuf:"varint,4,opt,name=vma_count,json=vmaCount,proto3" json:"vma_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProfilingResponse) Reset() {
	*x = StartProfilingResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProfilingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProfilingResponse) ProtoMessage() {}

func (x *StartProfilingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProfilingResponse.ProtoReflect.Descriptor instead.
func (*StartProfilingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *StartProfilingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartProfilingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StartProfilingResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StartProfilingResponse) GetVmaCount() int32 {
	if x != nil {
		return x.VmaCount
	}
	return 0
}

// StopProfilingRequest is empty
type StopProfilingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProfilingRequest) Reset() {
	*x = StopProfilingRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProfilingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProfilingRequest) ProtoMessage() {}

func (x *StopProfilingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProfilingRequest.ProtoReflect.Descriptor instead.
func (*StopProfilingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{14}
}

// StopProfilingResponse contains the result of stopping profiling
type StopProfilingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProfilingResponse) Reset() {
	*x = StopProfilingResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProfilingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProfilingResponse) ProtoMessage() {}

func (x *StopProfilingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProfilingResponse.ProtoReflect.Descriptor instead.
func (*StopProfilingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *StopProfilingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetHotRegionsRequest is empty
type GetHotRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotRegionsRequest) Reset() {
	*x = GetHotRegionsRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRegionsRequest) ProtoMessage() {}

func (x *GetHotRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRegionsRequest.ProtoReflect.Descriptor instead.
func (*GetHotRegionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{16}
}

// GetHotRegionsResponse contains the current hot memory regions
type GetHotRegionsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Regions     []*HotRegionProto      `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	TotalVmas   int32                  `protobuf:"varint,3,opt,name=total_vmas,json=totalVmas,proto3" json:"total_vmas,omitempty"`
	HotVmas     int32                  `protobuf:"varint,4,opt,name=hot_vmas,json=hotVmas,proto3" json:"hot_vmas,omitempty"`
	// Full VMA details (hot + cold) for checkpoint metadata and prefetch priority
	VmaDetails    []*VMAHotInfo `protobuf:"bytes,5,rep,name=vma_details,json=vmaDetails,proto3" json:"vma_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotRegionsResponse) Reset() {
	*x = GetHotRegionsResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotRegionsResponse) ProtoMessage() {}

func (x *GetHotRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotRegionsResponse.ProtoReflect.Descriptor instead.
func (*GetHotRegionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *GetHotRegionsResponse) GetRegions() []*HotRegionProto {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *GetHotRegionsResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *GetHotRegionsResponse) GetTotalVmas() int32 {
	if x != nil {
		return x.TotalVmas
	}
	return 0
}

func (x *GetHotRegionsResponse) GetHotVmas() int32 {
	if x != nil {
		return x.HotVmas
	}
	return 0
}

func (x *GetHotRegionsResponse) GetVmaDetails() []*VMAHotInfo {
	if x != nil {
		return x.VmaDetails
	}
	return nil
}

// HotRegionProto represents a hot memory region
type HotRegionProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartAddr      uint64                 `protobuf:"varint,1,opt,name=start_addr,json=startAddr,proto3" json:"start_addr,omitempty"`
	EndAddr        uint64                 `protobuf:"varint,2,opt,name=end_addr,json=endAddr,proto3" json:"end_addr,omitempty"`
	WrittenRatio   float64                `protobuf:"fixed64,3,opt,name=written_ratio,json=writtenRatio,proto3" json:"written_ratio,omitempty"`
	ConsecutiveHot int32                  `protobuf:"varint,4,opt,name=consecutive_hot,json=consecutiveHot,proto3" json:"consecutive_hot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HotRegionProto) Reset() {
	*x = HotRegionProto{}
	mi := &file_pkg_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRegionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRegionProto) ProtoMessage() {}

func (x *HotRegionProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRegionProto.ProtoReflect.Descriptor instead.
func (*HotRegionProto) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *HotRegionProto) GetStartAddr() uint64 {
	if x != nil {
		return x.StartAddr
	}
	return 0
}

func (x *HotRegionProto) GetEndAddr() uint64 {
	if x != nil {
		return x.EndAddr
	}
	return 0
}

func (x *HotRegionProto) GetWrittenRatio() float64 {
	if x != nil {
		return x.WrittenRatio
	}
	return 0
}

func (x *HotRegionProto) GetConsecutiveHot() int32 {
	if x != nil {
		return x.ConsecutiveHot
	}
	return 0
}

// VMAHotInfo contains per-VMA hot/cold classification with dirty stats
type VMAHotInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartAddr      uint64                 `protobuf:"varint,1,opt,name=start_addr,json=startAddr,proto3" json:"start_addr,omitempty"`
	EndAddr        uint64                 `protobuf:"varint,2,opt,name=end_addr,json=endAddr,proto3" json:"end_addr,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "heap", "anonymous", "data", "stack", etc.
	Pathname       string                 `protobuf:"bytes,4,opt,name=pathname,proto3" json:"pathname,omitempty"`
	IsHot          bool                   `protobuf:"varint,5,opt,name=is_hot,json=isHot,proto3" json:"is_hot,omitempty"`
	DirtyPages     int64                  `protobuf:"varint,6,opt,name=dirty_pages,json=dirtyPages,proto3" json:"dirty_pages,omitempty"`
	TotalPages     int64                  `protobuf:"varint,7,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	DirtyRatio     float64                `protobuf:"fixed64,8,opt,name=dirty_ratio,json=dirtyRatio,proto3" json:"dirty_ratio,omitempty"`
	ConsecutiveHot int32                  `protobuf:"varint,9,opt,name=consecutive_hot,json=consecutiveHot,proto3" json:"consecutive_hot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VMAHotInfo) Reset() {
	*x = VMAHotInfo{}
	mi := &file_pkg_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMAHotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMAHotInfo) ProtoMessage() {}

func (x *VMAHotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMAHotInfo.ProtoReflect.Descriptor instead.
func (*VMAHotInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *VMAHotInfo) GetStartAddr() uint64 {
	if x != nil {
		return x.StartAddr
	}
	return 0
}

func (x *VMAHotInfo) GetEndAddr() uint64 {
	if x != nil {
		return x.EndAddr
	}
	return 0
}

func (x *VMAHotInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VMAHotInfo) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *VMAHotInfo) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *VMAHotInfo) GetDirtyPages() int64 {
	if x != nil {
		return x.DirtyPages
	}
	return 0
}

func (x *VMAHotInfo) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *VMAHotInfo) GetDirtyRatio() float64 {
	if x != nil {
		return x.DirtyRatio
	}
	return 0
}

func (x *VMAHotInfo) GetConsecutiveHot() int32 {
	if x != nil {
		return x.ConsecutiveHot
	}
	return 0
}

// GetDirtyVolumeRequest is empty
type GetDirtyVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirtyVolumeRequest) Reset() {
	*x = GetDirtyVolumeRequest{}
	mi := &file_pkg_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirtyVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirtyVolumeRequest) ProtoMessage() {}

func (x *GetDirtyVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirtyVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetDirtyVolumeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{20}
}

// GetDirtyVolumeResponse contains current dirty page statistics
type GetDirtyVolumeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DirtyPages           int64                  `protobuf:"varint,1,opt,name=dirty_pages,json=dirtyPages,proto3" json:"dirty_pages,omitempty"`
	DirtyBytes           int64                  `protobuf:"varint,2,opt,name=dirty_bytes,json=dirtyBytes,proto3" json:"dirty_bytes,omitempty"`
	DirtyRatePagesPerSec float64                `protobuf:"fixed64,3,opt,name=dirty_rate_pages_per_sec,json=dirtyRatePagesPerSec,proto3" json:"dirty_rate_pages_per_sec,omitempty"`
	CumulativeDirtyBytes int64                  `protobuf:"varint,4,opt,name=cumulative_dirty_bytes,json=cumulativeDirtyBytes,proto3" json:"cumulative_dirty_bytes,omitempty"`
	AvgDirtyRate         float64                `protobuf:"fixed64,5,opt,name=avg_dirty_rate,json=avgDirtyRate,proto3" json:"avg_dirty_rate,omitempty"`
	TimestampMs          int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetDirtyVolumeResponse) Reset() {
	*x = GetDirtyVolumeResponse{}
	mi := &file_pkg_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirtyVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirtyVolumeResponse) ProtoMessage() {}

func (x *GetDirtyVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirtyVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetDirtyVolumeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetDirtyVolumeResponse) GetDirtyPages() int64 {
	if x != nil {
		return x.DirtyPages
	}
	return 0
}

func (x *GetDirtyVolumeResponse) GetDirtyBytes() int64 {
	if x != nil {
		return x.DirtyBytes
	}
	return 0
}

func (x *GetDirtyVolumeResponse) GetDirtyRatePagesPerSec() float64 {
	if x != nil {
		return x.DirtyRatePagesPerSec
	}
	return 0
}

func (x *GetDirtyVolumeResponse) GetCumulativeDirtyBytes() int64 {
	if x != nil {
		return x.CumulativeDirtyBytes
	}
	return 0
}

func (x *GetDirtyVolumeResponse) GetAvgDirtyRate() float64 {
	if x != nil {
		return x.AvgDirtyRate
	}
	return 0
}

func (x *GetDirtyVolumeResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_pkg_proto_agent_proto protoreflect.FileDescriptor

const file_pkg_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/agent.proto\x12\x05agent\"^\n" +
	"\x14PreCheckpointRequest\x12$\n" +
	"\x0eparent_dump_id\x18\x01 \x01(\tR\fparentDumpId\x12 \n" +
	"\fupload_to_s3\x18\x02 \x01(\bR\n" +
	"uploadToS3\"\x90\x01\n" +
	"\x15PreCheckpointResponse\x12\x17\n" +
	"\adump_id\x18\x01 \x01(\tR\x06dumpId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fpages_dumped\x18\x04 \x01(\x03R\vpagesDumped\"\xe0\x01\n" +
	"\x10FinalDumpRequest\x12(\n" +
	"\x10page_server_addr\x18\x01 \x01(\tR\x0epageServerAddr\x12(\n" +
	"\x10page_server_port\x18\x02 \x01(\x05R\x0epageServerPort\x12$\n" +
	"\x0eparent_dump_id\x18\x03 \x01(\tR\fparentDumpId\x12#\n" +
	"\rleave_running\x18\x04 \x01(\bR\fleaveRunning\x12-\n" +
	"\x12migration_strategy\x18\x05 \x01(\tR\x11migrationStrategy\"\xc6\x03\n" +
	"\x11FinalDumpResponse\x12\x17\n" +
	"\adump_id\x18\x01 \x01(\tR\x06dumpId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12.\n" +
	"\x13metadata_size_bytes\x18\x03 \x01(\x03R\x11metadataSizeBytes\x12U\n" +
	"\x0fexternal_mounts\x18\x04 \x03(\v2,.agent.FinalDumpResponse.ExternalMountsEntryR\x0eexternalMounts\x12&\n" +
	"\x0fpage_server_pid\x18\x05 \x01(\x05R\rpageServerPid\x12I\n" +
	"\vpipe_inodes\x18\x06 \x03(\v2(.agent.FinalDumpResponse.PipeInodesEntryR\n" +
	"pipeInodes\x1aA\n" +
	"\x13ExternalMountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPipeInodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x04\n" +
	"\x0eRestoreRequest\x12\x17\n" +
	"\adump_id\x18\x01 \x01(\tR\x06dumpId\x12\x1b\n" +
	"\ts3_bucket\x18\x02 \x01(\tR\bs3Bucket\x12\x1b\n" +
	"\ts3_prefix\x18\x03 \x01(\tR\bs3Prefix\x12$\n" +
	"\x0euse_lazy_pages\x18\x04 \x01(\bR\fuseLazyPages\x12(\n" +
	"\x10page_server_port\x18\x05 \x01(\x05R\x0epageServerPort\x12\x1f\n" +
	"\vsource_addr\x18\x06 \x01(\tR\n" +
	"sourceAddr\x12R\n" +
	"\x0fexternal_mounts\x18\a \x03(\v2).agent.RestoreRequest.ExternalMountsEntryR\x0eexternalMounts\x12-\n" +
	"\x12migration_strategy\x18\b \x01(\tR\x11migrationStrategy\x12F\n" +
	"\vpipe_inodes\x18\t \x03(\v2%.agent.RestoreRequest.PipeInodesEntryR\n" +
	"pipeInodes\x1aA\n" +
	"\x13ExternalMountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPipeInodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x0fRestoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anew_pid\x18\x02 \x01(\x05R\x06newPid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\x0f\n" +
	"\rStatusRequest\"\xbd\x02\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12(\n" +
	"\x10main_process_pid\x18\x02 \x01(\x05R\x0emainProcessPid\x12,\n" +
	"\x12last_checkpoint_id\x18\x03 \x01(\tR\x10lastCheckpointId\x124\n" +
	"\x16checkpoint_chain_depth\x18\x04 \x01(\x05R\x14checkpointChainDepth\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12\x19\n" +
	"\bpod_name\x18\x06 \x01(\tR\apodName\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\x12*\n" +
	"\x11lazy_pages_active\x18\b \x01(\bR\x0flazyPagesActive\"f\n" +
	"\x11PageServerRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12%\n" +
	"\x0echeckpoint_dir\x18\x02 \x01(\tR\rcheckpointDir\x12\x16\n" +
	"\x06daemon\x18\x03 \x01(\bR\x06daemon\"T\n" +
	"\x12PageServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"+\n" +
	"\x17PageServerStatusRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"y\n" +
	"\x18PageServerStatusResponse\x12\x19\n" +
	"\bis_alive\x18\x01 \x01(\bR\aisAlive\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\"\x86\x01\n" +
	"\x15StartProfilingRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\x12#\n" +
	"\rhot_threshold\x18\x02 \x01(\x01R\fhotThreshold\x12'\n" +
	"\x0fhot_consecutive\x18\x03 \x01(\x05R\x0ehotConsecutive\"w\n" +
	"\x16StartProfilingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1b\n" +
	"\tvma_count\x18\x04 \x01(\x05R\bvmaCount\"\x16\n" +
	"\x14StopProfilingRequest\"1\n" +
	"\x15StopProfilingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14GetHotRegionsRequest\"\xd9\x01\n" +
	"\x15GetHotRegionsResponse\x12/\n" +
	"\aregions\x18\x01 \x03(\v2\x15.agent.HotRegionProtoR\aregions\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"total_vmas\x18\x03 \x01(\x05R\ttotalVmas\x12\x19\n" +
	"\bhot_vmas\x18\x04 \x01(\x05R\ahotVmas\x122\n" +
	"\vvma_details\x18\x05 \x03(\v2\x11.agent.VMAHotInfoR\n" +
	"vmaDetails\"\x98\x01\n" +
	"\x0eHotRegionProto\x12\x1d\n" +
	"\n" +
	"start_addr\x18\x01 \x01(\x04R\tstartAddr\x12\x19\n" +
	"\bend_addr\x18\x02 \x01(\x04R\aendAddr\x12#\n" +
	"\rwritten_ratio\x18\x03 \x01(\x01R\fwrittenRatio\x12'\n" +
	"\x0fconsecutive_hot\x18\x04 \x01(\x05R\x0econsecutiveHot\"\x99\x02\n" +
	"\n" +
	"VMAHotInfo\x12\x1d\n" +
	"\n" +
	"start_addr\x18\x01 \x01(\x04R\tstartAddr\x12\x19\n" +
	"\bend_addr\x18\x02 \x01(\x04R\aendAddr\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bpathname\x18\x04 \x01(\tR\bpathname\x12\x15\n" +
	"\x06is_hot\x18\x05 \x01(\bR\x05isHot\x12\x1f\n" +
	"\vdirty_pages\x18\x06 \x01(\x03R\n" +
	"dirtyPages\x12\x1f\n" +
	"\vtotal_pages\x18\a \x01(\x03R\n" +
	"totalPages\x12\x1f\n" +
	"\vdirty_ratio\x18\b \x01(\x01R\n" +
	"dirtyRatio\x12'\n" +
	"\x0fconsecutive_hot\x18\t \x01(\x05R\x0econsecutiveHot\"\x17\n" +
	"\x15GetDirtyVolumeRequest\"\x91\x02\n" +
	"\x16GetDirtyVolumeResponse\x12\x1f\n" +
	"\vdirty_pages\x18\x01 \x01(\x03R\n" +
	"dirtyPages\x12\x1f\n" +
	"\vdirty_bytes\x18\x02 \x01(\x03R\n" +
	"dirtyBytes\x126\n" +
	"\x18dirty_rate_pages_per_sec\x18\x03 \x01(\x01R\x14dirtyRatePagesPerSec\x124\n" +
	"\x16cumulative_dirty_bytes\x18\x04 \x01(\x03R\x14cumulativeDirtyBytes\x12$\n" +
	"\x0eavg_dirty_rate\x18\x05 \x01(\x01R\favgDirtyRate\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs2\xe3\x05\n" +
	"\tCRIUAgent\x12J\n" +
	"\rPreCheckpoint\x12\x1b.agent.PreCheckpointRequest\x1a\x1c.agent.PreCheckpointResponse\x12>\n" +
	"\tFinalDump\x12\x17.agent.FinalDumpRequest\x1a\x18.agent.FinalDumpResponse\x128\n" +
	"\aRestore\x12\x15.agent.RestoreRequest\x1a\x16.agent.RestoreResponse\x128\n" +
	"\tGetStatus\x12\x14.agent.StatusRequest\x1a\x15.agent.StatusResponse\x12F\n" +
	"\x0fStartPageServer\x12\x18.agent.PageServerRequest\x1a\x19.agent.PageServerResponse\x12X\n" +
	"\x15CheckPageServerStatus\x12\x1e.agent.PageServerStatusRequest\x1a\x1f.agent.PageServerStatusResponse\x12M\n" +
	"\x0eStartProfiling\x12\x1c.agent.StartProfilingRequest\x1a\x1d.agent.StartProfilingResponse\x12J\n" +
	"\rStopProfiling\x12\x1b.agent.StopProfilingRequest\x1a\x1c.agent.StopProfilingResponse\x12J\n" +
	"\rGetHotRegions\x12\x1b.agent.GetHotRegionsRequest\x1a\x1c.agent.GetHotRegionsResponse\x12M\n" +
	"\x0eGetDirtyVolume\x12\x1c.agent.GetDirtyVolumeRequest\x1a\x1d.agent.GetDirtyVolumeResponseB7Z5github.com/ddps-lab/criu-migration-operator/pkg/protob\x06proto3"

var (
	file_pkg_proto_agent_proto_rawDescOnce sync.Once
	file_pkg_proto_agent_proto_rawDescData []byte
)

func file_pkg_proto_agent_proto_rawDescGZIP() []byte {
	file_pkg_proto_agent_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)))
	})
	return file_pkg_proto_agent_proto_rawDescData
}

var file_pkg_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pkg_proto_agent_proto_goTypes = []any{
	(*PreCheckpointRequest)(nil),     // 0: agent.PreCheckpointRequest
	(*PreCheckpointResponse)(nil),    // 1: agent.PreCheckpointResponse
	(*FinalDumpRequest)(nil),         // 2: agent.FinalDumpRequest
	(*FinalDumpResponse)(nil),        // 3: agent.FinalDumpResponse
	(*RestoreRequest)(nil),           // 4: agent.RestoreRequest
	(*RestoreResponse)(nil),          // 5: agent.RestoreResponse
	(*StatusRequest)(nil),            // 6: agent.StatusRequest
	(*StatusResponse)(nil),           // 7: agent.StatusResponse
	(*PageServerRequest)(nil),        // 8: agent.PageServerRequest
	(*PageServerResponse)(nil),       // 9: agent.PageServerResponse
	(*PageServerStatusRequest)(nil),  // 10: agent.PageServerStatusRequest
	(*PageServerStatusResponse)(nil), // 11: agent.PageServerStatusResponse
	(*StartProfilingRequest)(nil),    // 12: agent.StartProfilingRequest
	(*StartProfilingResponse)(nil),   // 13: agent.StartProfilingResponse
	(*StopProfilingRequest)(nil),     // 14: agent.StopProfilingRequest
	(*StopProfilingResponse)(nil),    // 15: agent.StopProfilingResponse
	(*GetHotRegionsRequest)(nil),     // 16: agent.GetHotRegionsRequest
	(*GetHotRegionsResponse)(nil),    // 17: agent.GetHotRegionsResponse
	(*HotRegionProto)(nil),           // 18: agent.HotRegionProto
	(*VMAHotInfo)(nil),               // 19: agent.VMAHotInfo
	(*GetDirtyVolumeRequest)(nil),    // 20: agent.GetDirtyVolumeRequest
	(*GetDirtyVolumeResponse)(nil),   // 21: agent.GetDirtyVolumeResponse
	nil,                              // 22: agent.FinalDumpResponse.ExternalMountsEntry
	nil,                              // 23: agent.FinalDumpResponse.PipeInodesEntry
	nil,                              // 24: agent.RestoreRequest.ExternalMountsEntry
	nil,                              // 25: agent.RestoreRequest.PipeInodesEntry
}
var file_pkg_proto_agent_proto_depIdxs = []int32{
	22, // 0: agent.FinalDumpResponse.external_mounts:type_name -> agent.FinalDumpResponse.ExternalMountsEntry
	23, // 1: agent.FinalDumpResponse.pipe_inodes:type_name -> agent.FinalDumpResponse.PipeInodesEntry
	24, // 2: agent.RestoreRequest.external_mounts:type_name -> agent.RestoreRequest.ExternalMountsEntry
	25, // 3: agent.RestoreRequest.pipe_inodes:type_name -> agent.RestoreRequest.PipeInodesEntry
	18, // 4: agent.GetHotRegionsResponse.regions:type_name -> agent.HotRegionProto
	19, // 5: agent.GetHotRegionsResponse.vma_details:type_name -> agent.VMAHotInfo
	0,  // 6: agent.CRIUAgent.PreCheckpoint:input_type -> agent.PreCheckpointRequest
	2,  // 7: agent.CRIUAgent.FinalDump:input_type -> agent.FinalDumpRequest
	4,  // 8: agent.CRIUAgent.Restore:input_type -> agent.RestoreRequest
	6,  // 9: agent.CRIUAgent.GetStatus:input_type -> agent.StatusRequest
	8,  // 10: agent.CRIUAgent.StartPageServer:input_type -> agent.PageServerRequest
	10, // 11: agent.CRIUAgent.CheckPageServerStatus:input_type -> agent.PageServerStatusRequest
	12, // 12: agent.CRIUAgent.StartProfiling:input_type -> agent.StartProfilingRequest
	14, // 13: agent.CRIUAgent.StopProfiling:input_type -> agent.StopProfilingRequest
	16, // 14: agent.CRIUAgent.GetHotRegions:input_type -> agent.GetHotRegionsRequest
	20, // 15: agent.CRIUAgent.GetDirtyVolume:input_type -> agent.GetDirtyVolumeRequest
	1,  // 16: agent.CRIUAgent.PreCheckpoint:output_type -> agent.PreCheckpointResponse
	3,  // 17: agent.CRIUAgent.FinalDump:output_type -> agent.FinalDumpResponse
	5,  // 18: agent.CRIUAgent.Restore:output_type -> agent.RestoreResponse
	7,  // 19: agent.CRIUAgent.GetStatus:output_type -> agent.StatusResponse
	9,  // 20: agent.CRIUAgent.StartPageServer:output_type -> agent.PageServerResponse
	11, // 21: agent.CRIUAgent.CheckPageServerStatus:output_type -> agent.PageServerStatusResponse
	13, // 22: agent.CRIUAgent.StartProfiling:output_type -> agent.StartProfilingResponse
	15, // 23: agent.CRIUAgent.StopProfiling:output_type -> agent.StopProfilingResponse
	17, // 24: agent.CRIUAgent.GetHotRegions:output_type -> agent.GetHotRegionsResponse
	21, // 25: agent.CRIUAgent.GetDirtyVolume:output_type -> agent.GetDirtyVolumeResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_agent_proto_init() }
func file_pkg_proto_agent_proto_init() {
	if File_pkg_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agent_proto_rawDesc), len(file_pkg_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agent_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agent_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agent_proto_msgTypes,
	}.Build()
	File_pkg_proto_agent_proto = out.File
	file_pkg_proto_agent_proto_goTypes = nil
	file_pkg_proto_agent_proto_depIdxs = nil
}
