// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CRIUAgent_PreCheckpoint_FullMethodName         = "/agent.CRIUAgent/PreCheckpoint"
	CRIUAgent_FinalDump_FullMethodName             = "/agent.CRIUAgent/FinalDump"
	CRIUAgent_Restore_FullMethodName               = "/agent.CRIUAgent/Restore"
	CRIUAgent_GetStatus_FullMethodName             = "/agent.CRIUAgent/GetStatus"
	CRIUAgent_StartPageServer_FullMethodName       = "/agent.CRIUAgent/StartPageServer"
	CRIUAgent_CheckPageServerStatus_FullMethodName = "/agent.CRIUAgent/CheckPageServerStatus"
	CRIUAgent_StartProfiling_FullMethodName        = "/agent.CRIUAgent/StartProfiling"
	CRIUAgent_StopProfiling_FullMethodName         = "/agent.CRIUAgent/StopProfiling"
	CRIUAgent_GetHotRegions_FullMethodName         = "/agent.CRIUAgent/GetHotRegions"
	CRIUAgent_GetDirtyVolume_FullMethodName        = "/agent.CRIUAgent/GetDirtyVolume"
)

// CRIUAgentClient is the client API for CRIUAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CRIUAgent service provides checkpoint and restore operations
type CRIUAgentClient interface {
	// PreCheckpoint performs an incremental pre-checkpoint
	PreCheckpoint(ctx context.Context, in *PreCheckpointRequest, opts ...grpc.CallOption) (*PreCheckpointResponse, error)
	// FinalDump performs the final dump with page-server
	FinalDump(ctx context.Context, in *FinalDumpRequest, opts ...grpc.CallOption) (*FinalDumpResponse, error)
	// Restore restores a process from a checkpoint
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// GetStatus returns the current status of the agent
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// StartPageServer starts the page-server for lazy restore
	StartPageServer(ctx context.Context, in *PageServerRequest, opts ...grpc.CallOption) (*PageServerResponse, error)
	// CheckPageServerStatus checks if a page-server process is still running
	CheckPageServerStatus(ctx context.Context, in *PageServerStatusRequest, opts ...grpc.CallOption) (*PageServerStatusResponse, error)
	// StartProfiling starts memory write profiling on the main process
	StartProfiling(ctx context.Context, in *StartProfilingRequest, opts ...grpc.CallOption) (*StartProfilingResponse, error)
	// StopProfiling stops memory write profiling
	StopProfiling(ctx context.Context, in *StopProfilingRequest, opts ...grpc.CallOption) (*StopProfilingResponse, error)
	// GetHotRegions returns currently identified hot memory regions
	GetHotRegions(ctx context.Context, in *GetHotRegionsRequest, opts ...grpc.CallOption) (*GetHotRegionsResponse, error)
	// GetDirtyVolume returns current dirty page statistics
	GetDirtyVolume(ctx context.Context, in *GetDirtyVolumeRequest, opts ...grpc.CallOption) (*GetDirtyVolumeResponse, error)
}

type cRIUAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewCRIUAgentClient(cc grpc.ClientConnInterface) CRIUAgentClient {
	return &cRIUAgentClient{cc}
}

func (c *cRIUAgentClient) PreCheckpoint(ctx context.Context, in *PreCheckpointRequest, opts ...grpc.CallOption) (*PreCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCheckpointResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_PreCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) FinalDump(ctx context.Context, in *FinalDumpRequest, opts ...grpc.CallOption) (*FinalDumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalDumpResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_FinalDump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) StartPageServer(ctx context.Context, in *PageServerRequest, opts ...grpc.CallOption) (*PageServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageServerResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_StartPageServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) CheckPageServerStatus(ctx context.Context, in *PageServerStatusRequest, opts ...grpc.CallOption) (*PageServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageServerStatusResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_CheckPageServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) StartProfiling(ctx context.Context, in *StartProfilingRequest, opts ...grpc.CallOption) (*StartProfilingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProfilingResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_StartProfiling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) StopProfiling(ctx context.Context, in *StopProfilingRequest, opts ...grpc.CallOption) (*StopProfilingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopProfilingResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_StopProfiling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) GetHotRegions(ctx context.Context, in *GetHotRegionsRequest, opts ...grpc.CallOption) (*GetHotRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotRegionsResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_GetHotRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRIUAgentClient) GetDirtyVolume(ctx context.Context, in *GetDirtyVolumeRequest, opts ...grpc.CallOption) (*GetDirtyVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDirtyVolumeResponse)
	err := c.cc.Invoke(ctx, CRIUAgent_GetDirtyVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRIUAgentServer is the server API for CRIUAgent service.
// All implementations must embed UnimplementedCRIUAgentServer
// for forward compatibility.
//
// CRIUAgent service provides checkpoint and restore operations
type CRIUAgentServer interface {
	// PreCheckpoint performs an incremental pre-checkpoint
	PreCheckpoint(context.Context, *PreCheckpointRequest) (*PreCheckpointResponse, error)
	// FinalDump performs the final dump with page-server
	FinalDump(context.Context, *FinalDumpRequest) (*FinalDumpResponse, error)
	// Restore restores a process from a checkpoint
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// GetStatus returns the current status of the agent
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	// StartPageServer starts the page-server for lazy restore
	StartPageServer(context.Context, *PageServerRequest) (*PageServerResponse, error)
	// CheckPageServerStatus checks if a page-server process is still running
	CheckPageServerStatus(context.Context, *PageServerStatusRequest) (*PageServerStatusResponse, error)
	// StartProfiling starts memory write profiling on the main process
	StartProfiling(context.Context, *StartProfilingRequest) (*StartProfilingResponse, error)
	// StopProfiling stops memory write profiling
	StopProfiling(context.Context, *StopProfilingRequest) (*StopProfilingResponse, error)
	// GetHotRegions returns currently identified hot memory regions
	GetHotRegions(context.Context, *GetHotRegionsRequest) (*GetHotRegionsResponse, error)
	// GetDirtyVolume returns current dirty page statistics
	GetDirtyVolume(context.Context, *GetDirtyVolumeRequest) (*GetDirtyVolumeResponse, error)
	mustEmbedUnimplementedCRIUAgentServer()
}

// UnimplementedCRIUAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCRIUAgentServer struct{}

func (UnimplementedCRIUAgentServer) PreCheckpoint(context.Context, *PreCheckpointRequest) (*PreCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreCheckpoint not implemented")
}
func (UnimplementedCRIUAgentServer) FinalDump(context.Context, *FinalDumpRequest) (*FinalDumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalDump not implemented")
}
func (UnimplementedCRIUAgentServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedCRIUAgentServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCRIUAgentServer) StartPageServer(context.Context, *PageServerRequest) (*PageServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPageServer not implemented")
}
func (UnimplementedCRIUAgentServer) CheckPageServerStatus(context.Context, *PageServerStatusRequest) (*PageServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPageServerStatus not implemented")
}
func (UnimplementedCRIUAgentServer) StartProfiling(context.Context, *StartProfilingRequest) (*StartProfilingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProfiling not implemented")
}
func (UnimplementedCRIUAgentServer) StopProfiling(context.Context, *StopProfilingRequest) (*StopProfilingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProfiling not implemented")
}
func (UnimplementedCRIUAgentServer) GetHotRegions(context.Context, *GetHotRegionsRequest) (*GetHotRegionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotRegions not implemented")
}
func (UnimplementedCRIUAgentServer) GetDirtyVolume(context.Context, *GetDirtyVolumeRequest) (*GetDirtyVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirtyVolume not implemented")
}
func (UnimplementedCRIUAgentServer) mustEmbedUnimplementedCRIUAgentServer() {}
func (UnimplementedCRIUAgentServer) testEmbeddedByValue()                   {}

// UnsafeCRIUAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRIUAgentServer will
// result in compilation errors.
type UnsafeCRIUAgentServer interface {
	mustEmbedUnimplementedCRIUAgentServer()
}

func RegisterCRIUAgentServer(s grpc.ServiceRegistrar, srv CRIUAgentServer) {
	// If the following call pancis, it indicates UnimplementedCRIUAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CRIUAgent_ServiceDesc, srv)
}

func _CRIUAgent_PreCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).PreCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_PreCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).PreCheckpoint(ctx, req.(*PreCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_FinalDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).FinalDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_FinalDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).FinalDump(ctx, req.(*FinalDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_StartPageServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).StartPageServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_StartPageServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).StartPageServer(ctx, req.(*PageServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_CheckPageServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).CheckPageServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_CheckPageServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).CheckPageServerStatus(ctx, req.(*PageServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_StartProfiling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProfilingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).StartProfiling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_StartProfiling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).StartProfiling(ctx, req.(*StartProfilingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_StopProfiling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProfilingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).StopProfiling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_StopProfiling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).StopProfiling(ctx, req.(*StopProfilingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_GetHotRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).GetHotRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_GetHotRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).GetHotRegions(ctx, req.(*GetHotRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRIUAgent_GetDirtyVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirtyVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRIUAgentServer).GetDirtyVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRIUAgent_GetDirtyVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRIUAgentServer).GetDirtyVolume(ctx, req.(*GetDirtyVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CRIUAgent_ServiceDesc is the grpc.ServiceDesc for CRIUAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRIUAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.CRIUAgent",
	HandlerType: (*CRIUAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreCheckpoint",
			Handler:    _CRIUAgent_PreCheckpoint_Handler,
		},
		{
			MethodName: "FinalDump",
			Handler:    _CRIUAgent_FinalDump_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _CRIUAgent_Restore_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CRIUAgent_GetStatus_Handler,
		},
		{
			MethodName: "StartPageServer",
			Handler:    _CRIUAgent_StartPageServer_Handler,
		},
		{
			MethodName: "CheckPageServerStatus",
			Handler:    _CRIUAgent_CheckPageServerStatus_Handler,
		},
		{
			MethodName: "StartProfiling",
			Handler:    _CRIUAgent_StartProfiling_Handler,
		},
		{
			MethodName: "StopProfiling",
			Handler:    _CRIUAgent_StopProfiling_Handler,
		},
		{
			MethodName: "GetHotRegions",
			Handler:    _CRIUAgent_GetHotRegions_Handler,
		},
		{
			MethodName: "GetDirtyVolume",
			Handler:    _CRIUAgent_GetDirtyVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/agent.proto",
}
